/**
 * Matriz de Permisos por Rol en Oralyn
 */

const ROLES = {
  SUPERADMIN: 'SUPERADMIN',
  DUENO: 'DUENO',
  ASISTENTE_ODONTOLOGO: 'ASISTENTE_ODONTOLOGO',
  RECEPCIONISTA: 'RECEPCIONISTA'
}

// Permisos estructurados módulo.acción
const PERMISSIONS = {
  // Pacientes
  PATIENTS_READ: 'patients.read',
  PATIENTS_CREATE: 'patients.create',
  PATIENTS_UPDATE: 'patients.update',
  PATIENTS_DELETE: 'patients.delete',

  // Citas
  APPOINTMENTS_READ: 'appointments.read',
  APPOINTMENTS_CREATE: 'appointments.create',
  APPOINTMENTS_UPDATE: 'appointments.update',
  APPOINTMENTS_CANCEL: 'appointments.cancel',
  APPOINTMENTS_DELETE: 'appointments.delete',

  // Historias clínicas (Clínico)
  CLINICAL_RECORDS_READ: 'clinical_records.read',
  CLINICAL_RECORDS_CREATE: 'clinical_records.create',
  CLINICAL_RECORDS_UPDATE: 'clinical_records.update',

  // Tratamientos / Cotizaciones
  TREATMENTS_READ: 'treatments.read',
  TREATMENTS_CREATE: 'treatments.create',
  TREATMENTS_UPDATE: 'treatments.update',
  TREATMENTS_DELETE: 'treatments.delete',

  // Odontograma (Clínico)
  ODONTOGRAM_READ: 'odontogram.read',
  ODONTOGRAM_UPDATE: 'odontogram.update',

  // CUPS / Catálogos
  CUPS_READ: 'cups.read',

  // RIPS
  RIPS_READ: 'rips.read',
  RIPS_CREATE: 'rips.create',

  // Adjuntos
  ATTACHMENTS_READ: 'attachments.read',
  ATTACHMENTS_CREATE: 'attachments.create',

  // Consentimientos y Certificados
  CONSENTIMIENTOS_READ: 'consentimientos.read',
  CONSENTIMIENTOS_CREATE: 'consentimientos.create',
  CERTIFICADOS_READ: 'certificados.read',
  CERTIFICADOS_CREATE: 'certificados.create',

  // Pagos y Facturas
  PAYMENTS_READ: 'payments.read',
  PAYMENTS_CREATE: 'payments.create',
  PAYMENTS_UPDATE: 'payments.update',

  INVOICES_READ: 'invoices.read',
  INVOICES_CREATE: 'invoices.create',
  INVOICES_UPDATE: 'invoices.update',

  // Usuarios del consultorio
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DISABLE: 'users.disable',
  USERS_REACTIVATE: 'users.reactivate',

  // Auditoría
  AUDIT_READ: 'audit.read',
  AUDIT_READ_GLOBAL: 'audit.read_global',

  // Configuración del consultorio
  SETTINGS_READ: 'settings.read',
  SETTINGS_UPDATE: 'settings.update',

  // Superadministración Plataforma
  SUPERADMIN_MANAGE_CONSULTORIOS: 'superadmin.consultorios',
  SUPERADMIN_MANAGE_PLATFORM: 'superadmin.platform'
}

const ROLE_PERMISSIONS = {
  [ROLES.SUPERADMIN]: [
    PERMISSIONS.SUPERADMIN_MANAGE_CONSULTORIOS,
    PERMISSIONS.SUPERADMIN_MANAGE_PLATFORM,
    PERMISSIONS.AUDIT_READ_GLOBAL,
    PERMISSIONS.SETTINGS_READ
    // RESTRICCIÓN DE SEGURIDAD IMPORTANTE: El SUPERADMIN NO tiene acceso a datos clínicos de los pacientes
  ],

  [ROLES.DUENO]: [
    // Pacientes
    PERMISSIONS.PATIENTS_READ, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_UPDATE, PERMISSIONS.PATIENTS_DELETE,
    // Citas
    PERMISSIONS.APPOINTMENTS_READ, PERMISSIONS.APPOINTMENTS_CREATE, PERMISSIONS.APPOINTMENTS_UPDATE, PERMISSIONS.APPOINTMENTS_CANCEL, PERMISSIONS.APPOINTMENTS_DELETE,
    // Historias clínicas
    PERMISSIONS.CLINICAL_RECORDS_READ, PERMISSIONS.CLINICAL_RECORDS_CREATE, PERMISSIONS.CLINICAL_RECORDS_UPDATE,
    // Tratamientos
    PERMISSIONS.TREATMENTS_READ, PERMISSIONS.TREATMENTS_CREATE, PERMISSIONS.TREATMENTS_UPDATE, PERMISSIONS.TREATMENTS_DELETE,
    // Odontograma
    PERMISSIONS.ODONTOGRAM_READ, PERMISSIONS.ODONTOGRAM_UPDATE,
    // Catálogos, RIPS, Adjuntos
    PERMISSIONS.CUPS_READ, PERMISSIONS.RIPS_READ, PERMISSIONS.RIPS_CREATE, PERMISSIONS.ATTACHMENTS_READ, PERMISSIONS.ATTACHMENTS_CREATE,
    // Consentimientos / Certificados
    PERMISSIONS.CONSENTIMIENTOS_READ, PERMISSIONS.CONSENTIMIENTOS_CREATE, PERMISSIONS.CERTIFICADOS_READ, PERMISSIONS.CERTIFICADOS_CREATE,
    // Pagos y Facturas
    PERMISSIONS.PAYMENTS_READ, PERMISSIONS.PAYMENTS_CREATE, PERMISSIONS.PAYMENTS_UPDATE,
    PERMISSIONS.INVOICES_READ, PERMISSIONS.INVOICES_CREATE, PERMISSIONS.INVOICES_UPDATE,
    // Gestión de usuarios
    PERMISSIONS.USERS_READ, PERMISSIONS.USERS_CREATE, PERMISSIONS.USERS_UPDATE, PERMISSIONS.USERS_DISABLE, PERMISSIONS.USERS_REACTIVATE,
    // Auditoría del consultorio
    PERMISSIONS.AUDIT_READ,
    // Configuración del consultorio
    PERMISSIONS.SETTINGS_READ, PERMISSIONS.SETTINGS_UPDATE
  ],

  [ROLES.ASISTENTE_ODONTOLOGO]: [
    // Pacientes
    PERMISSIONS.PATIENTS_READ, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_UPDATE,
    // Citas
    PERMISSIONS.APPOINTMENTS_READ, PERMISSIONS.APPOINTMENTS_CREATE, PERMISSIONS.APPOINTMENTS_UPDATE,
    // Historias clínicas
    PERMISSIONS.CLINICAL_RECORDS_READ, PERMISSIONS.CLINICAL_RECORDS_CREATE, PERMISSIONS.CLINICAL_RECORDS_UPDATE,
    // Tratamientos
    PERMISSIONS.TREATMENTS_READ, PERMISSIONS.TREATMENTS_CREATE, PERMISSIONS.TREATMENTS_UPDATE,
    // Odontograma
    PERMISSIONS.ODONTOGRAM_READ, PERMISSIONS.ODONTOGRAM_UPDATE,
    // Catálogos, RIPS, Adjuntos
    PERMISSIONS.CUPS_READ, PERMISSIONS.RIPS_READ, PERMISSIONS.RIPS_CREATE, PERMISSIONS.ATTACHMENTS_READ, PERMISSIONS.ATTACHMENTS_CREATE,
    // Consentimientos / Certificados
    PERMISSIONS.CONSENTIMIENTOS_READ, PERMISSIONS.CONSENTIMIENTOS_CREATE, PERMISSIONS.CERTIFICADOS_READ, PERMISSIONS.CERTIFICADOS_CREATE,
    // Pagos / Facturas (Lectura básica)
    PERMISSIONS.PAYMENTS_READ, PERMISSIONS.INVOICES_READ
  ],

  [ROLES.RECEPCIONISTA]: [
    // Pacientes (lectura, creación, edición admin)
    PERMISSIONS.PATIENTS_READ, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_UPDATE,
    // Citas
    PERMISSIONS.APPOINTMENTS_READ, PERMISSIONS.APPOINTMENTS_CREATE, PERMISSIONS.APPOINTMENTS_UPDATE, PERMISSIONS.APPOINTMENTS_CANCEL,
    // Tratamientos / Cotizaciones
    PERMISSIONS.TREATMENTS_READ, PERMISSIONS.TREATMENTS_CREATE,
    // Consentimientos
    PERMISSIONS.CONSENTIMIENTOS_READ, PERMISSIONS.CONSENTIMIENTOS_CREATE,
    // Pagos y Facturación
    PERMISSIONS.PAYMENTS_READ, PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.INVOICES_READ, PERMISSIONS.INVOICES_CREATE,
    // Ajustes / Catálogos
    PERMISSIONS.SETTINGS_READ
  ]
}

function hasPermission(role, permission) {
  if (!role || !ROLE_PERMISSIONS[role]) return false
  return ROLE_PERMISSIONS[role].includes(permission)
}

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission
}
