-- AlterTable
ALTER TABLE "HcAntecedentes" ALTER COLUMN "tratamiento_medicacion" DROP NOT NULL,
ALTER COLUMN "tratamiento_medicacion" DROP DEFAULT,
ALTER COLUMN "reacciones_alergicas" DROP NOT NULL,
ALTER COLUMN "reacciones_alergicas" DROP DEFAULT,
ALTER COLUMN "problemas_coagulacion" DROP NOT NULL,
ALTER COLUMN "problemas_coagulacion" DROP DEFAULT,
ALTER COLUMN "irradiaciones" DROP NOT NULL,
ALTER COLUMN "irradiaciones" DROP DEFAULT,
ALTER COLUMN "tension_arterial" DROP NOT NULL,
ALTER COLUMN "tension_arterial" DROP DEFAULT,
ALTER COLUMN "sinusitis" DROP NOT NULL,
ALTER COLUMN "sinusitis" DROP DEFAULT,
ALTER COLUMN "enf_respiratorias" DROP NOT NULL,
ALTER COLUMN "enf_respiratorias" DROP DEFAULT,
ALTER COLUMN "cardiopatias" DROP NOT NULL,
ALTER COLUMN "cardiopatias" DROP DEFAULT,
ALTER COLUMN "diabetes" DROP NOT NULL,
ALTER COLUMN "diabetes" DROP DEFAULT,
ALTER COLUMN "fiebre_reumatica" DROP NOT NULL,
ALTER COLUMN "fiebre_reumatica" DROP DEFAULT,
ALTER COLUMN "hepatitis" DROP NOT NULL,
ALTER COLUMN "hepatitis" DROP DEFAULT,
ALTER COLUMN "vih" DROP NOT NULL,
ALTER COLUMN "vih" DROP DEFAULT,
ALTER COLUMN "trastornos_emocionales" DROP NOT NULL,
ALTER COLUMN "trastornos_emocionales" DROP DEFAULT;

-- AlterTable
ALTER TABLE "HistoriaClinica" ADD COLUMN     "acudiente" TEXT,
ADD COLUMN     "alergias" TEXT,
ADD COLUMN     "departamento" TEXT,
ADD COLUMN     "direccion" TEXT,
ADD COLUMN     "eps" TEXT,
ADD COLUMN     "estado_civil" TEXT,
ADD COLUMN     "ocupacion" TEXT,
ADD COLUMN     "parentesco" TEXT,
ADD COLUMN     "rh" TEXT,
ADD COLUMN     "tipo_afiliacion" TEXT,
ADD COLUMN     "tipo_sangre" TEXT;
