export const ROLES = {
  SUPERADMIN: 'SUPERADMIN',
  DUENO: 'DUENO',
  ASISTENTE_ODONTOLOGO: 'ASISTENTE_ODONTOLOGO',
  RECEPCIONISTA: 'RECEPCIONISTA'
}

export const ROLE_LABELS = {
  SUPERADMIN: 'Superadministrador',
  DUENO: 'Dueño / Administrador',
  ASISTENTE_ODONTOLOGO: 'Asistente / Odontólogo',
  RECEPCIONISTA: 'Recepcionista'
}

export const PERMISSIONS = {
  PATIENTS_READ: 'patients.read',
  PATIENTS_CREATE: 'patients.create',
  PATIENTS_UPDATE: 'patients.update',
  PATIENTS_DELETE: 'patients.delete',

  APPOINTMENTS_READ: 'appointments.read',
  APPOINTMENTS_CREATE: 'appointments.create',
  APPOINTMENTS_UPDATE: 'appointments.update',
  APPOINTMENTS_CANCEL: 'appointments.cancel',

  CLINICAL_RECORDS_READ: 'clinical_records.read',
  CLINICAL_RECORDS_CREATE: 'clinical_records.create',
  CLINICAL_RECORDS_UPDATE: 'clinical_records.update',

  TREATMENTS_READ: 'treatments.read',
  TREATMENTS_CREATE: 'treatments.create',
  TREATMENTS_UPDATE: 'treatments.update',

  ODONTOGRAM_READ: 'odontogram.read',
  ODONTOGRAM_UPDATE: 'odontogram.update',

  CONSENTIMIENTOS_READ: 'consentimientos.read',
  CONSENTIMIENTOS_CREATE: 'consentimientos.create',

  CERTIFICADOS_READ: 'certificados.read',
  CERTIFICADOS_CREATE: 'certificados.create',

  PAYMENTS_READ: 'payments.read',
  PAYMENTS_CREATE: 'payments.create',

  INVOICES_READ: 'invoices.read',
  INVOICES_CREATE: 'invoices.create',

  RIPS_READ: 'rips.read',
  RIPS_CREATE: 'rips.create',

  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DISABLE: 'users.disable',

  AUDIT_READ: 'audit.read',
  AUDIT_READ_GLOBAL: 'audit.read_global',

  SETTINGS_READ: 'settings.read',
  SETTINGS_UPDATE: 'settings.update',

  SUPERADMIN_MANAGE_CONSULTORIOS: 'superadmin.consultorios'
}

const ROLE_PERMISSIONS = {
  [ROLES.SUPERADMIN]: [
    PERMISSIONS.SUPERADMIN_MANAGE_CONSULTORIOS,
    PERMISSIONS.AUDIT_READ_GLOBAL,
    PERMISSIONS.SETTINGS_READ
  ],
  [ROLES.DUENO]: [
    PERMISSIONS.PATIENTS_READ, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_UPDATE, PERMISSIONS.PATIENTS_DELETE,
    PERMISSIONS.APPOINTMENTS_READ, PERMISSIONS.APPOINTMENTS_CREATE, PERMISSIONS.APPOINTMENTS_UPDATE, PERMISSIONS.APPOINTMENTS_CANCEL,
    PERMISSIONS.CLINICAL_RECORDS_READ, PERMISSIONS.CLINICAL_RECORDS_CREATE, PERMISSIONS.CLINICAL_RECORDS_UPDATE,
    PERMISSIONS.TREATMENTS_READ, PERMISSIONS.TREATMENTS_CREATE, PERMISSIONS.TREATMENTS_UPDATE,
    PERMISSIONS.ODONTOGRAM_READ, PERMISSIONS.ODONTOGRAM_UPDATE,
    PERMISSIONS.CONSENTIMIENTOS_READ, PERMISSIONS.CONSENTIMIENTOS_CREATE,
    PERMISSIONS.CERTIFICADOS_READ, PERMISSIONS.CERTIFICADOS_CREATE,
    PERMISSIONS.PAYMENTS_READ, PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.INVOICES_READ, PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.RIPS_READ, PERMISSIONS.RIPS_CREATE,
    PERMISSIONS.USERS_READ, PERMISSIONS.USERS_CREATE, PERMISSIONS.USERS_UPDATE, PERMISSIONS.USERS_DISABLE,
    PERMISSIONS.AUDIT_READ, PERMISSIONS.SETTINGS_READ, PERMISSIONS.SETTINGS_UPDATE
  ],
  [ROLES.ASISTENTE_ODONTOLOGO]: [
    PERMISSIONS.PATIENTS_READ, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_UPDATE,
    PERMISSIONS.APPOINTMENTS_READ, PERMISSIONS.APPOINTMENTS_CREATE, PERMISSIONS.APPOINTMENTS_UPDATE,
    PERMISSIONS.CLINICAL_RECORDS_READ, PERMISSIONS.CLINICAL_RECORDS_CREATE, PERMISSIONS.CLINICAL_RECORDS_UPDATE,
    PERMISSIONS.TREATMENTS_READ, PERMISSIONS.TREATMENTS_CREATE, PERMISSIONS.TREATMENTS_UPDATE,
    PERMISSIONS.ODONTOGRAM_READ, PERMISSIONS.ODONTOGRAM_UPDATE,
    PERMISSIONS.CONSENTIMIENTOS_READ, PERMISSIONS.CONSENTIMIENTOS_CREATE,
    PERMISSIONS.CERTIFICADOS_READ, PERMISSIONS.CERTIFICADOS_CREATE,
    PERMISSIONS.PAYMENTS_READ, PERMISSIONS.INVOICES_READ, PERMISSIONS.RIPS_READ,
    PERMISSIONS.SETTINGS_READ
  ],
  [ROLES.RECEPCIONISTA]: [
    PERMISSIONS.PATIENTS_READ, PERMISSIONS.PATIENTS_CREATE, PERMISSIONS.PATIENTS_UPDATE,
    PERMISSIONS.APPOINTMENTS_READ, PERMISSIONS.APPOINTMENTS_CREATE, PERMISSIONS.APPOINTMENTS_UPDATE, PERMISSIONS.APPOINTMENTS_CANCEL,
    PERMISSIONS.TREATMENTS_READ, PERMISSIONS.TREATMENTS_CREATE,
    PERMISSIONS.CONSENTIMIENTOS_READ, PERMISSIONS.CONSENTIMIENTOS_CREATE,
    PERMISSIONS.PAYMENTS_READ, PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.INVOICES_READ, PERMISSIONS.INVOICES_CREATE,
    PERMISSIONS.SETTINGS_READ
  ]
}

export function hasPermission(usuario, permission) {
  if (!usuario || !usuario.rol) return false
  const list = ROLE_PERMISSIONS[usuario.rol] || []
  return list.includes(permission)
}

export function hasRole(usuario, ...roles) {
  if (!usuario || !usuario.rol) return false
  return roles.includes(usuario.rol)
}
